Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04-arm64"

  config.vm.provider "parallels" do |prl|
    prl.cpus = 2
    prl.memory = 2048
  end

  config.vm.provision "shell", path: "vagrant-install.sh"
end
